name: Update Documentation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> .env
        echo "GH_ORG=${{ secrets.GH_ORG }}" >> .env
        echo "BITBUCKET_USERNAME=${{ secrets.BITBUCKET_USERNAME }}" >> .env
        echo "BITBUCKET_TOKEN=${{ secrets.BITBUCKET_TOKEN }}" >> .env
        echo "BITBUCKET_WORKSPACE=${{ secrets.BITBUCKET_WORKSPACE }}" >> .env
    
    - name: Run documentation update
      run: python run.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add docs_collection/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update documentation" && git push)